/* COMANDOS PARA CRIAR AS TABELAS */

CREATE TABLE users (
   id INT NOT NULL AUTO_INCREMENT,
   nome VARCHAR(255) NOT NULL,
   CPF VARCHAR(255) NOT NULL,
   responsavel BOOLEAN NOT NULL DEFAULT 0;
   -- telefone VARCHAR(255) NOT NULL,
   -- email VARCHAR(255) NOT NULL,
   -- CRO VARCHAR(255) NOT NULL,
   createdAt DATETIME,
   updatedAt DATETIME,
   permissao VARCHAR(255) NOT NULL,
   PRIMARY KEY (id)
);
/* INSERIR NOVA COLUNA NA TABELA users */
-- ALTER TABLE users
-- ADD nome_tabela varchar(255);

-- DROP TABLE users